### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by XhmikosR**
Also:

* switch to `^` for all deps
* add missing properties in package.json
* add lock file

### CODE REVIEW

**Comment by XhmikosR** [comment]
This definitely breaks some thing https://github.com/XhmikosR/changelog-maker/commit/6a0605414a3852afe146f1584ac5d3e955d075f4/checks

So, I'd say we add CI first, and then move with the rest.

**Comment by XhmikosR** [comment]
Ah, the failures must be because of an authorization issue. So, if this passes locally for people, it should be OK to merge. But perhaps we should specify an `engines` version while at it.

**Comment by XhmikosR** [comment]
@rvagg you don't want a package-lock.json file here? If so let me know and I'll adapt this

**Comment by rvagg** [comment]
@XhmikosR probably appropriate here, I think just update the gitexec dependency and this is good to go. I've added you as collaborator here so you can land your PRs when you get a 👍 from someone else, or at least you can't elicit a 👎. I assume you're familiar with the consensus seeking style around here—the difference being that this repo is likely to get less attention so it might just be me showing up with a 👍.

**Comment by XhmikosR** [comment]
@rvagg I'm having trouble running the tests locally. What's the exact procedure for this to work? It should probably be documented in README.md.

**Comment by rvagg** [comment]
> I'm having trouble running the tests locally.

right ... this is kind of complicated and we might need to adjust things for CI. Because changelog-maker pulls metadata from the GitHub API it needs an authentication token. When you first run it against a project that has the relevant metadata (`PR-URL` being one of the most important pieces of data in commits) then it _should_ prompt you for a GitHub login so it can make a token. That token gets stored in your local config directory (`~/.config/changelog-maker/config.json` on Linux and `~/Library/Application Support/changelog-maker/config.json` on macOS, somewhere else appropriate on Windows). So testing gets all of this stuff involved, which is fine for local testing but more complicated on CI. We'd either need to mock that out somehow, entirely remove it (making the tests less helpful) or store someone's auth token for use by GitHub Actions. We have one or two GH accounts for use by infra things in the nodejs org so could use one of those perhaps.

Happy to take advice on what you think we should do on this if you're keen to get CI working. Also, if you have trouble doing it locally let me know where it's getting hung up. And yes, we should put this on the README, it's just not fresh in my mind so it might be best to leave that to someone who has to do it from scratch.

**Comment by targos** [comment]
Github provides an API token in then environment of actions. Maybe we can dump it to the config file in a step?

**Comment by XhmikosR** [comment]
@targos yes, we need to use that. Let me try with `GITHUV_TOKEN` but maybe something more is needed.

@rvagg please try to understand the files addition is not in this PR, it's on #61. I just need the lock file here. That being said, I don't see how you don't see that adding useless files in the npm package does not help anyone. If one wants to develop a package, they will clone the repo. Regardless, I will revert the files change from #61 so that we move on, but I will bring it back separately.

This PR is for adding CI support.

**Comment by XhmikosR** [comment]
Let's move the CI discussion on #64 

I removed the files addition from here, so if someone could run this branch locally and tests pass, we can move on with merging it.

**Comment by XhmikosR** [comment]
Alright, this works for Ubuntu but fails on Windows. I'm not sure what's wrong on Windows and I still need the instructions including the token permissions documented, so I can't test locally on my Windows machine.

**Comment by XhmikosR** [comment]
Alright, I pinpointed the Windows failures. @rvagg it seems it's coming from gitexec 2.0.0

**Comment by XhmikosR** [comment]
More specifically from https://github.com/rvagg/gitexec/commit/51ad38d5f7b84f4b543719328fb487439616a7e9

So we need to fix this on gitexec and then update it here.

**Comment by XhmikosR** [comment]
I think we should tackle the gitexec update separately. We know for sure it breaks Windows testing and the exact patch.

**Pull request merged**
