### PR TITLE
chore(deps): remove package-lock.json

### PR DESCRIPTION
**Pull request by rvagg**
Includes the dependabot updates, but also a general remove and update for package-lock.json with the new format.

### CODE REVIEW

**Comment by targos** [comment]
Is there value in keeping a lockfile in this project? It has no effect on consumers who install it and I don't think we clone the repo to run it anywhere?

**Comment by rvagg** [comment]
yeah, good point, the intention was probably to keep the deps stable when publishing, but I don't think package-lock gets published, does it?

**Comment by targos** [comment]
no, it's completely ignored when we publish.

**Comment by targos** [comment]
I usually do this when a package-lock isn't useful: https://github.com/nodejs/node-core-utils/commit/08d3a5f9928420faece437d5431bf943fdaefc1e

**Comment by rvagg** [comment]
yeah, I have that in my global config and usually don't have them in my projects

**Comment by rvagg** [comment]
changed to `chore(deps): remove package-lock.json`

**Pull request merged**
